const RegistrationDummy = {
	default: {
		'email': 'qwe@qwe.qwe',
		'login': 'qwe',
		'password': 'qwe',
		'fio': 'qwe',
		'Pagetitle': 'DZ Staging',
		'CMD': '/?do=',
		'CMD_THIS': '/?do=registration',
		'STATIC': '/?page=',
		'INDEX': '/index.php',
		'MAIN': '/',
		'JSON': '/?do=registration&json',
		'ROOT': '',
		'ROOTQ': '/?',
		'VISUAL': '/visual/',
		'module': 'registration',
		'user': null,
		'tpl': 'registration',
		'resultingLogin': 'qwe',
		'resultingPassword': 'success',
		'success': true,
		'error': '',
	},

	alreadyExists: {
		'Pagetitle': 'Личный кабинет пользователя',
		'CMD': '/?do=',
		'CMD_THIS': '/?do=user',
		'STATIC': '/?page=',
		'INDEX': '/index.php',
		'MAIN': '/',
		'JSON': '/?do=user&json',
		'ROOT': '',
		'ROOTQ': '/?',
		'VISUAL': '/visual/',
		'module': 'user',
		'user': null,
		'tpl': 'user',
		'User': null,
	},
};

export default RegistrationDummy;
