version: "3.8"
services:
    frontend:
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - "3000:3000"
        command: npm run dev
        volumes:
            - /app/node_modules
            - ./src:/app/src
